version: '3.8'
services:
  redis:
    image: "redis:latest"
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: metrics_app
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    command: python metrics.py

volumes:
  redis_data:
